
[client]

	[client.firstperson]
		#Render dragon model in first person. If your own tail scares you, write false
		renderFirstPerson = true
		#Render dragon model in first person while gliding. We don't advise you to turn it on.
		renderFirstPersonFlight = false
		#Use rotation of your tail in first person, otherwise the tail is always opposite of your camera. If the tail is constantly climbing in your face, put false.
		firstPersonRotation = false

	[client.flight]
		#Should flight be activated when jumping in the air
		jumpToFly = false
		#Should the camera movement while gliding as a dragon be enabled
		flightCameraMovement = true
		#Should the rotation effect during gliding of other players be shown?
		renderOtherPlayerRotation = true
		#Should particles from your own spin attack be displayed for you?
		ownSpinParticles = true
		#Should the zoom effect while gliding as a dragon be enabled
		flightZoomEffect = true
		#Is it required to look up to start flying while jumping, requires that jumpToFly is on
		lookAtSkyForFlight = false
		#Should other players particles from spin attack be shown for you?
		othersSpinParticles = true
		#Notifies of wing status in chat message
		notifyWingStatus = false

	[client.ui]

		[client.ui.magic]
			#Offset the y position of the cast bar in relation to its normal position
			#Range: -1000 ~ 1000
			casterBarYPos = 0
			#Offset the x position of the cast bar in relation to its normal position
			#Range: -1000 ~ 1000
			casterBarXPos = 0
			#Offset the x position of the magic skill bar in relation to its normal position
			#Range: -1000 ~ 1000
			skillbarXOffset = 0
			#Offset the y position of the mana bar in relation to its normal position
			#Range: -1000 ~ 1000
			manabarYOffset = 0
			#Offset the x position of the mana bar in relation to its normal position
			#Range: -1000 ~ 1000
			manabarXOffset = 0
			#Offset the y position of the magic skill bar in relation to its normal position
			#Range: -1000 ~ 1000
			skillbarYOffset = 0

		[client.ui.emotes]
			#Offset the y position of the emote button in relation to its normal position
			#Range: -1000 ~ 1000
			emoteYOffset = 0
			#Offset the x position of the emote button in relation to its normal position
			#Range: -1000 ~ 1000
			emoteXOffset = 0

		[client.ui.spin]
			#Offset the x position of the spin cooldown indicator in relation to its normal position
			#Range: -1000 ~ 1000
			spinCooldownXOffset = 0
			#Offset the y position of the spin cooldown indicator in relation to its normal position
			#Range: -1000 ~ 1000
			spinCooldownYOffset = 0

		[client.ui.growth]
			#Offset the y position of the item growth icon in relation to its normal position
			#Range: -1000 ~ 1000
			growthYOffset = 0
			#Offset the x position of the item growth icon in relation to its normal position
			#Range: -1000 ~ 1000
			growthXOffset = 0

	[client.rendering]
		#Should other player skins be rendered?
		renderOtherPlayerSkins = true
		#Should the tools on the claws and teeth be rendered for your dragon?
		renderDragonClaws = true
		#Enable movement based physics on the tail, this is still a working progress and can be buggy.
		enableTailPhysics = true
		#Do you want your dragon skin to be rendered as a newborn dragon?
		renderNewbornSkin = true
		#Should items be rendered near the mouth of dragons rather then hovering by their side?
		renderItemsInMouth = false
		#Should the body rotate with the camera when turning around.
		rotateBodyWithCamera = true
		#Do you want your dragon skin to be rendered as a young dragon?
		renderYoungSkin = true
		#Do you want your dragon skin to be rendered as a adult dragon?
		renderAdultSkin = true
		#Should the armor be rendered as a layer on the dragon? Some shaders requires this to be off. Can cause some weird effects with armor when turned off.
		armorRenderLayer = true

	[client.inventory]
		#Should the third person item render for dragons use the default rotations? Use this if modded items are rendering weird when held.
		thirdPersonItemRender = false
		#Should the buttons for toggeling between dragon and normaly inventory be added?
		inventoryToggle = true
		#Should the default inventory be replaced as a dragon?
		dragonInventory = true
		#Should held items be rendered as if you are in third-person even in first person as a dragon?
		alternateHeldItem = false
		#Should dragon tabs be added to the default player inventory?
		dragonTabs = true

	[client.nametag]
		#Show name tags for dragons.
		dragonNameTags = false

	[client.tooltips]
		#Should the mod be allowed ot change the color and appearance of tooltips?
		tooltipChanges = true
		#Should the effect of the help tooltips be enabled?
		helpTooltips = true
		#Should dragon foods have their tooltip color changed to show which type of dragon can consume it?
		dragonFoodTooltips = true
		#Always show the help tooltip border
		alwaysShowHelpTooltip = false

	[client.misc]
		#Enable client-side debug messages
		clientDebugMessages = false
		#Disable this setting to disable support for appleskin as a dragon if it is causing ui issues
		appleskinSupport = true

